import { generateNames } from '../../helpers';

export default (id: string) => generateNames(
	id,
	'LABEL',
	'SMALL',
	'MEDIUM',
	'LARGE',
	'BOLD',
	'UPPERCASE',
	'UNDERLINE',
	'H1',
	'H2',
	'H3',
	'H4',
	'H5',
	'H6',
	'P',
	'DEFAULT_SMALL',
	'DEFAULT_SMALL_BOLD',
	'DEFAULT_REGULAR',
	'DEFAULT_REGULAR_BOLD',
	'DEFAULT_LARGE',
	'DEFAULT_LARGE_BOLD',
	'LABEL',
	'LABEL_BOLD',
	'LABEL_LARGE',
	'LABEL_LARGE_BOLD',
	'LABEL_SMALL',
);